### ISSUE TITLE
PHP Parse error 7.1 unexpected 'new' (T_NEW)

### ISSUE THREAD

**Issue by andyliuonline** [kitetail/zttp#55] opened 2017-12-25 03:51 UTC
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in 

vendor/kitetail/zttp/src/Zttp.php on line 9

Use PHP7.1

**Comment by adamwathan** [comment] 2017-12-25 15:13
Hmm my guess is you aren't actually using PHP 7+ like you think; support for methods named `new` was added in PHP 7.0 so maybe there are multiple versions installed in your environment and the wrong one is being used?

Everything runs on PHP 7.1.8 fine here:

![image](https://user-images.githubusercontent.com/4323180/34341000-345ed2c0-e95c-11e7-9bf5-868dfb31aff6.png)

Can you share a screenshot of what you see when you output `phpversion()` in your environment?

**Comment by OwenMelbz** [comment] 2018-03-31 09:02
@adamwathan 

I think its to do with the new reserved keywords, that are especially present in 7.2

If you run it through [php7cc](https://github.com/sstalle/php7cc) the usage of the ::new gets flagged up

e.g if i try use it from within my project

<img width="493" alt="illumipress____sites_hitachi-erd_vendor_owenmelbz_illumipress__-_____src_helpers_php__illumipress_" src="https://user-images.githubusercontent.com/1094740/38161615-3cdd2406-34ca-11e8-8178-c38b6d214e8f.png">

then check it with php7cc

<img width="592" alt="owen_mac-n-cheese____sites_hitachi-erd_vendor_owenmelbz_illumipress__zsh_" src="https://user-images.githubusercontent.com/1094740/38161625-68a7bf92-34ca-11e8-8efe-f27c7f648548.png">

Hopefully that helps shed some light :)

**Comment by simonhamp** [comment] 2018-06-04 09:24
> As of PHP 7.0.0 these keywords _are allowed_ as property, constant, and method names of classes, interfaces and traits, except that `class` may not be used as constant name.

[The PHP Manual](http://php.net/manual/en/reserved.keywords.php) (emphasis mine)

**Comment by OwenMelbz** [comment] 2018-06-04 09:29
@simonhamp They are allowed yeah :) but I don't think that's what the problem is about.

I believe its more about a tool that is being used, such as an IDE or linter is throwing up the error - otherwise IF the version being mentioned is actually the one being used in the browser, it would not fail

**Comment by adamwathan** [comment] 2018-06-04 14:20
This is totally valid in PHP 7+ and our tests all run without issue on PHP 7.2 so closing this.

**Closed as completed by adamwathan** 2018-06-04 14:20 UTC

**Comment by byrdacov** [comment] 2020-03-13 22:23
It fixes easily, check out the [solution](https://yablogo.su/wordpress/php-7-i-wordpress-kak-ispravit-neozhidannuyu-new-t_new-oshibku/)
